version: 2.1
commands:
  install_oracle_jdk:
    steps:
      # install java 8 see https://qiita.com/shinobu_shiva/items/a050a493a21ff73b35c6
      - run:
          name: Download Java
          command: |
            FILE=~/app.terminal-order.com/jdk-8u131-linux-x64.rpm
            if test -f "$FILE"; then
                echo "$FILE exists"
            else
                echo "$FILE not exists"
                wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm"
            fi
      - run:
          name: LocalInstall Java
          command: 'sudo yum localinstall jdk-8u131-linux-x64.rpm -y'
      # Javaをキャッシュする
      - save_cache:
          key: java-cache
          paths:
            - ~/app.terminal-order.com/jdk-8u131-linux-x64.rpm
      - run: sudo rm -f ~/app.terminal-order.com/*.rpm
      - run: java -version
      - run:
          name: Install sbt
          command: |
            curl -L --silent "https://github.com/sbt/sbt/releases/download/v1.4.9/sbt-1.4.9.tgz" > ~/sbt.tgz
            tar zxf ~/sbt.tgz -C ~/
            sudo ln -s ~/sbt/bin/sbt /usr/local/bin/sbt
      - run: sudo yum install gcc-c++ make -y
      - run: curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
      - run: sudo yum install -y nodejs
      - run: node -v
jobs:
  build:
    working_directory: ~/app.terminal-order.com
    docker:
      - image: amazonlinux:latest
        environment:
          _JAVA_OPTIONS: -Xms4096M -Xmx4096M
          JAVA_HOME: /usr/java/latest
          JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
          TZ: Asia/Tokyo
      - image: circleci/mysql:5.7
        environment:
          TZ: Asia/Tokyo
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: terminal
          MYSQL_USER: terminal
          MYSQL_PASSWORD: oppV34S496ECuyqeEz5N5y09m54
          DB_HOST: 127.0.0.1
        command: [--character-set-server=utf8, --collation-server=utf8_general_ci, --default-storage-engine=innodb]

    steps:
      - run: yum install sudo wget yum-utils git tar jq procps -y
      - install_oracle_jdk
      - checkout
      - run:
          name: install mysql client
          command: |
              sudo yum localinstall https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm -y
              sudo yum-config-manager --disable mysql80-community
              sudo yum-config-manager --enable mysql57-community
              sudo yum install mysql-community-client -y
              mysql --version
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
      # - run: echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
      - run:
          command: |
            while true; do
              sleep 2
              $JAVA_HOME/bin/jps
              pid=$($JAVA_HOME/bin/jps | grep 'sbt-launch.jar' | awk '{print $1}')
              $JAVA_HOME/bin/jcmd $pid Thread.print
              echo "======"
            done
          background: true

      - run:
          command: |
            while true; do
              sleep 2
              $JAVA_HOME/bin/jps
              pid=$($JAVA_HOME/bin/jps | grep 'sbt-launch.jar' | awk '{print $1}')
              sudo $JAVA_HOME/bin/jcmd $pid GC.class_histogram
              echo "======"
            done
          background: true
      - run:
          name: sbt version
          command: sbt sbtVersion
      - run:
          name: sbt compile
          command: cat /dev/null | sbt compile
      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.sbt
          key: v1-dependencies-{{ checksum "build.sbt" }}
      - run:
          name: sbt test
          command: cat /dev/null | sbt test --debug

      - run:
          name: check dead lock
          when: on_fail
          command: |
              mysql -h localhost --port 3306 --protocol tcp -u root --execute='SELECT trx_rows_locked FROM information_schema.INNODB_TRX;'
